### ISSUE TITLE
The FUTURE

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#101]
What should I do next?

- Work on the SHELF screen. It's not friendly. It's confusing. What is this thing? What are all the images?
- Document / write tutorials.
- Work on the new user experience. It should feel much better than now.
- Look at all the open issues and close if appropriate.
- Contemplate redoing the entire MUSIC gui. Writing music is just terrible right now.

**Comment by Camto** [comment]
I'm all for this https://github.com/script-8/script-8.github.io/issues/41 .

**Comment by gabrielflorit** [comment]
That looks super cool. But I don't know how to use it! I do love the aesthetics.

**Comment by TBD** [comment]
@gabrielflorit click on soniccharge logo and on the first post in the forum there is a video. also there are more demo songs there.

what I love in JS80TRX:
* piano roll with glide support
* simple instrument editor (multiple oscillator + arpeggiator)
* song made of rows of 3 patterns (easy to make progressive songs)
* SPACE for quick play/pause
* retro look
* small one JS inside HTML

bummer that it doesn't work on Safari/macOS

**Comment by gabrielflorit** [comment]
thank you for the detail, going to check this out

**Comment by gabrielflorit** [comment]
this is now covered by various open + closed issues, e.g. #118
