### ISSUE TITLE
Cannot use slider

### ISSUE THREAD

**Issue by oueouiiaoo** [script-8/script-8.github.io#109]
I can't find a way to activate the slider for numbers, i've tried highlighting, clicking and holding right clicking, and holding Ctrl and Shift, But i can't get the slider to appear.

Is this is bug ?

**Comment by gabrielflorit** [comment]
Sorry it's not documented (yet). Try clicking on a number then hold Meta, which on a mac is the Command key. Not sure what is in on windows. I will check.

**Comment by gabrielflorit** [comment]
It's Control on windows. It wasn't working before. Fixed. Sorry for that.

**Comment by oueouiiaoo** [comment]
Thanks!
