### ISSUE TITLE
add light theme

### ISSUE THREAD

**Issue by TBD** [script-8/script-8.github.io#112]
a light theme is needed and more contrast to be able to read the text

here is filter:invert() on body
<img width="980" alt="clipboard" src="https://user-images.githubusercontent.com/7951/51166636-e06a1180-18ac-11e9-8c05-07e34e468fe1.png">

**Comment by gabrielflorit** [comment]
oh interesting, i had never thought of that. and this is still only using the 8 colors?

**Comment by TBD** [comment]
filter:invert() was just a quick hack on everything to show how it looks on a lighter theme.

maybe invert just parts of the UI and keep the default palette – but is more manual work to do 😜

**Comment by Kethku** [comment]
Note: If this is implemented, thought will need to be given toward redesigning getPixel since it has a hard coded value for the background.
