### ISSUE TITLE
Add CODE tabs

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#140]
It's a pain to have all the code in just one screen.

**Comment by colxi** [comment]
I agree.
In order to be able to perform complex developments, tabs would be seriously helpful.
Code folding, and an actual scrollbar in the code area, would help too.

**Comment by gabrielflorit** [comment]
Code folding is on its way as well. A scrollbar should be there now. You don't see it?

**Comment by colxi** [comment]
J've just double checked, and i can't see the scrollbar

Tested in : 
Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Windows 10

**Comment by gabrielflorit** [comment]
Oh you're right! It hasn't bothered me before. I actually prefer the visual look of no scrollbar. But I can see how it's a confusing GUI element. Let me think about this.

**Comment by colxi** [comment]
I have to admit that the effort yo put into creating a beautiful GUI ended with successful results. 
I really like how simple, and intuitive became, but in my opinion if you expect people to perform complex implementations, where the length of you code extends by far, beyond the viewport height, the lack of a scrollbar makes the navigation of your code a nightmare.

I'm working on this, right now ;
https://script-8.github.io/?id=39fecddb0beeca75700d5b9d38247b05

I'm not even at 50% of the implementation yet, and i already have >600 lines of code.  Scroll from the top to the bottom, takes me about 4-5 seconds, each time. It's painfully unproductive.

If you finally decide to not implement the scrollbar, i'm pretty sure the upcoming code tabs and code folding, would help a lot.

**Comment by gabrielflorit** [comment]
Thank you for the kind words, much appreciated.

The lack of the scrollbar ... is not intentional! To be honest I have no idea how it disappeared. I'll see what it looks like when I put it back.

Code tabs are coming! Maybe today!!

**Comment by colxi** [comment]
I'm looking forward to it!

**Comment by colxi** [comment]
With this CSS  rule, the scrollbar appears again in the editor
```
.CodeMirror-scroll {
    width: 100%;
}
```
Some extra CSS to make it respect the style and palette of the application 

```
::-webkit-scrollbar-thumb {
    background: #20394f;
    border-left: 1px solid #15456b;
}
::-webkit-scrollbar-track {
    background: #0f2a3f;
}
```

**Comment by gabrielflorit** [comment]
Code tabs is coming: https://github.com/script-8/script-8.github.io/tree/codetabs-in-gameobject

**Comment by gabrielflorit** [comment]
closed by https://github.com/script-8/script-8.github.io/pull/196
