### ISSUE TITLE
Accessing a HELP tutorial (platformer) wiped my sprite that I hadn't saved

### ISSUE THREAD

**Issue by icarito** [script-8/script-8.github.io#147]
I'm enjoying the project - just happened to me that I wanted to access some kind of code reference (just realized at the HELP tab itself!) - but I clicked the platformer tutorial. Then my unsaved sprite was gone.

Thanks again!

**Comment by gabrielflorit** [comment]
Oh, right. Sorry about that. I'll work on a fix.
