### ISSUE TITLE
Ability to modify core pallette

### ISSUE THREAD

**Issue by joelvanveluwen** [script-8/script-8.github.io#151]
It would be cool to have some flexibility with the palette. Perhaps you could assign colours to the 8 colour options via a colour picker. The current palette is super pretty but limits the aesthetics a little.

**Comment by gabrielflorit** [comment]
Thank you for the feedback. At the moment there are no immediate plans to change the palette, but nothing is set in stone. I can see this happening in the future, once other issues get taken care of.
