### ISSUE TITLE
More palette choices

### ISSUE THREAD

**Issue by DeadlyDad** [script-8/script-8.github.io#160]
While I really appreciate the effort that went into this project, the default palette is... rather muddy, let's say.    Some options to change it up:

1. Offer a 'cassette setup' option to completely change the #RRGGBB _palette_ for a given cassette.
2. Offer a 'cassette setup' option to completely change the #RRGGBB _tint_ for a given cassette.  (Still a monochrome scale, but coders can set, for example, a light blue tint to it, instead of the default beige.)
3. Add a 'setPalette' command to choose which of the 16/32/64/etc. official colours are to be used.  [Here](https://lospec.com/palette-list) is a *excellent* selection.  (I especially like DawnBringer's 8/16/32 palettes.)
4. (Optionally) offer a 1-bit 256x256 mode.

Hope this helps!
Keith Olson

**Comment by icarito** [comment]
![image](https://user-images.githubusercontent.com/199755/52172168-0cecad00-2738-11e9-9c2a-67810b3c4428.png)
*Here's how it looks with a naive replace for DB8 palette.*

It'd be cool to be able to switch them. One complication is that the UI (at least the drawing tools) should get the palette from the console palette, currently they're defined separately. Love `nyx` but for small children I need some extra color, thanks!

Here's the branch with the switched palette:
https://github.com/script-8/script-8.github.io/compare/dev...icarito:DB8_palette?expand=1

**Comment by gabrielflorit** [comment]
I like the vibrant colors!

Not sure I am ready to allow more than nyx8, but this is the kind of example to help me down that direction.

Re: UI and game palette, you're right, but if we store the palette in the redux store, then the UI would just grab it from there.

**Comment by gabrielflorit** [comment]
I should test on non-vibrant monitors. I bet non-retina devices do make the palette look muddy.

**Comment by icarito** [comment]
I appreciate the artist stance on allowing other palettes. One argument for flexibility on this point is that colors are a cultural expression. I would hesitate to work with indigenous people and imposing a palette on them. Just a thought.

**Comment by gabrielflorit** [comment]
Going to close this for now, as I have no immediate plans to support different palettes.
