### ISSUE TITLE
Add pagination to cassettes API endpoint

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#168]
otherwise soon we will have users downloading megas and megas

**Comment by icarito** [comment]
Where is the code for this ? :-D

**Comment by gabrielflorit** [comment]
Somewhere! Why?

**Comment by icarito** [comment]
I'm not happy with using Gists as backend and looking for alternatives - #172 

I tried to publish my [github fork to github pages](https://script-8.educa.juegos/) and it works more or less but Github auth doesn't work!

;-)

:rocket: 

Regards!

**Comment by gabrielflorit** [comment]
Oh I see. https://github.com/gabrielflorit/script-8-api

**Comment by gabrielflorit** [comment]
No:

- requesting 5 cassettes takes 1.36s
- requesting 260 takes 1.51s

At least for now, it's much better to keep them all around and avoid multiple slow requests.
