### ISSUE TITLE
SHELF isn't displaying games

### ISSUE THREAD

**Issue by AsherGomez** [script-8/script-8.github.io#169]
Hello, the SHELF tab isn't displaying the games. Please fix this.

P.S. SCRIPT-8 is amazing!

**Comment by gabrielflorit** [comment]
Hi @AsherGomez , sorry to hear this. I see games on SHELF. Is this still happening? Maybe there was a database outing earlier. Let me check.

**Comment by AsherGomez** [comment]
Yes, it's still happening.

**Comment by gabrielflorit** [comment]
I'm unable to replicate this. What browser and OS are you using? Can you share a screenshot of the error?

**Comment by AsherGomez** [comment]
I'm on Chrome, here is a screenshot:
[image: SCRIPT-8.png]

**Comment by AsherGomez** [comment]
Also, sorry for taking a while to respond. Normally when I send a message
like this it takes forever for them to respond.

**Comment by AsherGomez** [comment]
You are  pretty prompt.

**Comment by gabrielflorit** [comment]
Looks like the screenshot didn't make it through. Also, what version of SCRIPT-8 are you running? You can find that on the home page, right under the logo to the right.

**Comment by AsherGomez** [comment]
Ok, hang on.

**Comment by AsherGomez** [comment]
v0.1.183

**Comment by gabrielflorit** [comment]
That's the latest one. Hmmm. Could you do something else? Open Chrome's console (in Chrome, do View > Developer > Javascript Console.

Now, with that open, refresh script-8, then click on SHELF. What do you see in console? Do you see an error? If so, can you send that to me?

**Comment by AsherGomez** [comment]
Ok, I'll try.

**Comment by AsherGomez** [comment]
[image: SCRIPT-8.png]

**Comment by AsherGomez** [comment]
It's fixed, thanks! I can see them now.
[image: SCRIPT-8.png]
