### ISSUE TITLE
Flip vertically

### ISSUE THREAD

**Issue by SlashScreen** [script-8/script-8.github.io#170]
I am now reminding you to allow the sprites to flip vertically, as promised

**Comment by gabrielflorit** [comment]
Hello! and great, thank you. this will be an easy fix too. cc @grantlouisherman !

**Comment by grantlouisherman** [comment]
Ill take a look after the highlighting one is done

**Comment by gabrielflorit** [comment]
closed by https://github.com/script-8/script-8.github.io/pull/212
