### ISSUE TITLE
Menu buttons aren't disabled during network requests

### ISSUE THREAD

**Issue by benwiley4000** [script-8/script-8.github.io#185]
I love this tool..

I also didn't realize I'm saving a new gist every time I hit save and now my list of gists on my github page is completely polluted with script-8 stuff I probably didn't want to share individually.

Any chance this could be saved into a repo instead? :smiley:

**Comment by gabrielflorit** [comment]
Hmmm. If you click RECORD it saves the same gist. If you click RECORD TO BLANK it forks. So if you only work on one cassette, you'll only have one gist.

I ... don't think I can easily write to repos! Is there another way of handling this?

**Comment by benwiley4000** [comment]
Maybe it was because I pressed record to blank a bunch of times? Also the menu is a bit unresponsive so I might have clicked a bunch of times and saved a bunch of duplicates.

**Comment by gabrielflorit** [comment]
Ah, I think what's happening is the fork button doesn't get disabled during the fetch request. Doh. That's an easy fix.

**Comment by benwiley4000** [comment]
Aha! Also the effect of the different options in the menu is a bit unclear. A ux problem after all. Thanks! :)

**Comment by gabrielflorit** [comment]
Now that I fixed https://github.com/script-8/script-8.github.io/issues/127, this is probably not an issue. Closing.
