### ISSUE TITLE
Compile to JS langs?

### ISSUE THREAD

**Issue by Camto** [script-8/script-8.github.io#186]
Would it be easy/interesting/a good idea to add extra compile to JS languages to SCRIPT-8? An example would be some kind of Lisp, which still doesn't have a fantasy console. Would work with the functional, pure approach here. Maybe even TypeScript.

**Comment by gabrielflorit** [comment]
lisp would definitely be interesting. The compile part would have to happen before the code gets evaluated, so it can be JS sent to the update/draw loop. I'm not opposed - interesting idea for sure.

**Comment by gabrielflorit** [comment]
CLosing this - won't get it to it for years.
