### ISSUE TITLE
A way to access the pixel data and set pixels directly

### ISSUE THREAD

**Issue by Kethku** [script-8/script-8.github.io#187]
I was wondering if there was any way to query the game for what pixel is set at a given location. I've written a physics engine in Pico8 that I was thinking of porting over, but it used the pixel data to determine collisions. I was disappointed to learn there was no way to access the pixel data in script-8.

I did some minor digging in the source and I suspect it shouldn't be too hard to implement. Any reason why I shouldn't dig in and try to build such a feature?

**Comment by gabrielflorit** [comment]
No, that sounds like a worthy addition. I suspect it would be fairly straightforward.

**Comment by gabrielflorit** [comment]
This is the drawing API: https://github.com/script-8/script-8.github.io/blob/dev/src/iframe/src/canvasAPI/index.js

**Comment by Kethku** [comment]
Sweet. I will get started on it tomorrow.

**Comment by Kethku** [comment]
I made a PR which adds getPixel and setPixel apis.

**Comment by gabrielflorit** [comment]
closed by https://github.com/script-8/script-8.github.io/pull/190
