### ISSUE TITLE
Following Development Instructions Fails on Windows 10

### ISSUE THREAD

**Issue by Kethku** [script-8/script-8.github.io#188]
I was trying to do some experiments adding new functions to script-8. The instructions on the readme say to install dependencies with yarn, and then run `yarn run iframe-start`. Unfortunately this produces this error:

```
yarn run v1.13.0
$ npm-run-all -p iframe-start-js iframe-watch-css
$ cd src/iframe; react-scripts start
$ cd src/iframe; stylus src/css/Iframe.styl -o src/css -w
The system cannot find the path specified.
The system cannot find the path specified.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "iframe-start-js" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm doing some investigation, but I'm not super familiar with the react-scripts package.

**Comment by gabrielflorit** [comment]
I think you need to install `stylus` as well. [stylus](https://www.npmjs.com/package/stylus)

If that works I'll update the README.

**Comment by Kethku** [comment]
Unfortunately after installing stylus with `npm install -g stylus` I still get the same error. I'm doing some further investigation.

**Comment by Kethku** [comment]
Welp looks like its a windows thing. If you don't set the script-shell config in npm to bash, then the paths don't get setup correctly to find packages in the node_modules folder. For any future people struggling, the fix for me was to install Git for Windows in order to have a bash install, then run:

```
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
```
Yarn still doesn't work (maybe yarn has it's own config?) but when I run the script via npm it works.

**Comment by gabrielflorit** [comment]
Glad you got it working. Care to issue a PR to include your note on the README?

**Comment by Kethku** [comment]
Of course. I will do it later this afternoon

**Comment by Kethku** [comment]
Done
