### ISSUE TITLE
Add input pressed buttons

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#203]
e.g. `input.right` and `input.rightPressed`

**Comment by Kethku** [comment]
Glorious :+1: this cuts down my marching squares demo a ton!

**Comment by Kethku** [comment]
I'll try to take a stab at implementing this later this afternoon

**Comment by Kethku** [comment]
This should be closed as it was implemented by https://github.com/script-8/script-8.github.io/pull/204

**Comment by gabrielflorit** [comment]
This is live now @Kethku

**Comment by Kethku** [comment]
Awesome! Updated my crate. Much better :)
