### ISSUE TITLE
Camera function is buggy

### ISSUE THREAD

**Issue by Kethku** [script-8/script-8.github.io#222]
I am still working on a minimal cassette demonstrating it, but when drawing sprites and changing the camera position, the screen can flicker. Also getPixel seems to get confused when the camera is changed.

**Comment by Kethku** [comment]
Okeydokey I've done some testing and I think I have figured it out.

The weirdness is that getPixel and setPixel happen in different coordinate spaces when the camera translation is set. https://script-8.github.io/?id=7e2ce058b18a78e08d4d24403189f05f is an example of what I am talking about.

```JavaScript
draw = () => {
  clear();
  camera(5, 0);
  setPixel(5, 5, 5);
  print(50, 50, getPixel(5, 5)); // Prints 7 not 5
}
```

Intuitively, setPixel and getPixel should refer to the same pixel regardless of the position of the camera. Unfortunately setPixel is in world space while getPixel is in cameraSpace.

**Comment by Kethku** [comment]
I still haven't tracked down the flicker issue, but once I fix this one it might help...

**Comment by Kethku** [comment]
Fix for getPixel: https://github.com/script-8/script-8.github.io/pull/228
Fix for camera flicker: https://github.com/script-8/script-8.github.io/pull/229

**Comment by gabrielflorit** [comment]
Thanks for the quick fixes!
