### ISSUE TITLE
Script-8 should set a <title>

### ISSUE THREAD

**Issue by icarito** [script-8/script-8.github.io#258]
If cassettes `//title` comments result in main window title being updated then users will be able to browse their games from their browser history or bookmarks. Looking it up...
Syntax: `document.title = 'Hello!'; // New title :)`

**Comment by gabrielflorit** [comment]
Oh! Clever. Yes I like it.

**Comment by icarito** [comment]
Served :plate_with_cutlery: 
https://github.com/script-8/script-8.github.io/pull/259 
Thanks!
