### ISSUE TITLE
Make sound editing more user-friendly

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#262]
It is pretty awful to edit more than a couple notes. The clicking! We need to do something.

Ideas:

- Add a CLEAR button to phrases, chains, and songs.
- If you have 63 phrases, and want to add phrase 1 to a cell, you have to click... 63 times!!! How to avoid this?
- There should be a way to clear a cell in one operation.
- There should be a way to choose where to put the playhead.
- There should be a way to clone/copy a phrase/chain/song.
- It should be one or two clicks to fill an entire row with one note.

Concrete implementation solutions:

- Add CLEAR button to right of grid (with a confirmation).
- Add LOAD button to right of grid (with confirmation).
- Add + / - buttons to right of grid, just like in SPRITE.
- Add playhead buttons above (i.e. add borders on the playhead) and make them clickable, which will take you to a specific part.
- Add a "selected" number to right of grid. In PHRASE, this would be an octave+volume. In CHAIN, a phrase. In SONG, a chain. Then, if you have + selected, and you click on an empty cell, the "selected" number goes in that cell. If you click on the cell again, you'd cycle down from there, as per usual right now.
- Add line/border every 4 columns.
- On mousedrag, fill the cells. (but according to what criteria)

**Comment by thykka** [comment]
As a user, I would like to be able to copy a phrase's notes/settings into another, so that I can easily create variations of an existing phrase.

**Comment by gabrielflorit** [comment]
This is done now.
