### ISSUE TITLE
Touch controls trigger user select

### ISSUE THREAD

**Issue by icarito** [script-8/script-8.github.io#267]
On Android chromium and Firefox!
Please include these styles:
```
            user-select: none;
            -webkit-user-select: none;
```
The latter for older Android devices. Otherwise buttons are unusable.

**Comment by gabrielflorit** [comment]
Odd, I thought I had done that. Will check again.

**Comment by icarito** [comment]
Sorry I had not tested this again I guess you fixed this recently!
