### ISSUE TITLE
Start new code with a template

### ISSUE THREAD

**Issue by jean-philippe-martin** [script-8/script-8.github.io#279]
When we start a new "blank" cassette, instead of an actually blank page for the code it may be useful to have an empty `init`, `update`, and `draw` function. This helps the beginners (no need to remember the signature), and speeds things up for everyone since we're going to write those sooner to later.

**Comment by gabrielflorit** [comment]
Great idea.

**Comment by gabrielflorit** [comment]
@jean-philippe-martin Let me know what you think.
