### ISSUE TITLE
Do not show update modal on games that have updated

### ISSUE THREAD

**Issue by jean-philippe-martin** [script-8/script-8.github.io#280]
It gets in the way of playing, and most people who clicked that link want to play, not code.

**Comment by gabrielflorit** [comment]
Could you give an example of this happening? with screenshots if possible.

**Comment by gabrielflorit** [comment]
OK this is still happening. Load any cassette in incognito mode and you get the update modal.

The update modal should only happen:

- if you're logged in
- and if you're the owner of the cassette
- and you haven't dismissed this notice
