### ISSUE TITLE
Add colorSwap to API

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#283]
How about this:

```
colorSwap(from, to)
  Swaps one color with another. Applies to any drawing calls. Reset with `colorSwap()`.

colorSwap()
  Resets any previous color swaps.
```

@Kethku if I understand your frame buffer renderer, everything goes through `setPixel`, correct? So to add this `colorSwap`, I only need to modify the `setPixel` function?

**Comment by Kethku** [comment]
Yes that's correct. I can make a PR making the change if you like

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
