### ISSUE TITLE
Delete Gist Error

### ISSUE THREAD

**Issue by Setherizor** [script-8/script-8.github.io#288]
When you have a private/public cassette, and delete the gist it is linked to (accidentally or otherwise) there is no way to remove those listings on the shelf.

When this happens the program gets stuck at booting cassette as expected.

Need a way to remove cassettes

**Comment by gabrielflorit** [comment]
I see. I should add a "remove from shelf" or something similar.

**Comment by gabrielflorit** [comment]
related to https://github.com/script-8/script-8.github.io/issues/242

**Comment by gabrielflorit** [comment]
Done
