### ISSUE TITLE
map() call doesn't respect y coordinate

### ISSUE THREAD

**Issue by cakenggt** [script-8/script-8.github.io#289]
https://github.com/script-8/script-8.github.io/blob/a60a494976db12e65cc21517b9637b05a0d858a8/src/iframe/src/contextCanvasAPI/index.js#L117
https://github.com/script-8/script-8.github.io/blob/bc69e066f0afb58a8acb34fe50672afe09441805/src/iframe/src/frameBufferCanvasAPI/index.js#L169

In the above two files, the `map` function doesn't take into account the `y` coordinate passed in.

**Comment by gabrielflorit** [comment]
I finally deployed this fix. Let me know if it works as expected.

**Comment by cakenggt** [comment]
script-8.github.io still seems to be loading up iframe version 0.1.255 for me.

**Comment by gabrielflorit** [comment]
Can you try in incognito or refreshing? I see 0.1.256 now.

**Comment by cakenggt** [comment]
Hmm even in incognito with this link https://script-8.github.io/?id=3209f14f4eb3bcd3abcf92c0f7281a62 I get the old version. Maybe it's taking a while to update the caching for me or something.

**Comment by gabrielflorit** [comment]
Oh, no, that's by design, otherwise existing cassettes would stop working with breaking API changes. To update to the latest API, go to CASSETTE > UPDATE.

**Comment by cakenggt** [comment]
Oh thanks! I'll do that now!

**Comment by cakenggt** [comment]
Yep it works for me! I had no idea it required an update when the api changes.
