### ISSUE TITLE
Menus stay open on mobile

### ISSUE THREAD

**Issue by thykka** [script-8/script-8.github.io#292]
Steps to reproduce:

1. Using Chrome or Firefox for Android, open up Script-8.

1. Tap the "Code" tab

1. Tap to focus the code editor

Expected behavior:

- The Code menu closes, as it no longer has focus

Actual behavior:

- The Code menu stays open, obstructing the code editor. 

Notes:

- Menu does not close even when writing code into the editor.

- The menu does close if the user does a tap-and-hold on the code editor.

**Comment by gabrielflorit** [comment]
Hmm, I see. How annoying!

**Comment by gabrielflorit** [comment]
This is surprisingly tricky because of how mobile treats the `hover` selector.

**Comment by gabrielflorit** [comment]
I don't think I'll be able to fix this at the moment. But I added a SHOW MENU button under the cassette, when in RUN mode, that is somewhat related. Still, not a perfect fix.
