### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by matimati433** [script-8/script-8.github.io#58]
`npm audit` shows that there are 11 vulnerabilities in SCRIPT-8's packages. Upgrading `react-scripts` to 1.1.4 fixes most of them: `npm install react-scripts@1.1.4`
After upgrading, there are only 2:
Critical - `macaddress` - Command Injection Vulnerability - [Node Security advisory link](https://nodesecurity.io/advisories/654)
Moderate - `base64url` - Out-of-bounds Read Vulnerability - [Node Security advisory link](https://nodesecurity.io/advisories/658)
`gh-pages` requires `base64url`.
The path for macaddress:
```
react-scripts > css-loader > cssnano >postcss-filter-plugins > uniqid > macaddress
```
`base64url` can also be fixed by upgrading to >= 3.0.0
However, `macaddress` hasn't got any patch it's vulnerability.

- [x] Fix the vulnerability in `macaddress`
- [ ] Fix the vulnerability in `base64url`

**Comment by gabrielflorit** [comment]
Thanks for this.

According to facebook, `macaddress` is not being used in a vulnerable way here: https://github.com/facebook/create-react-app/issues/4479.

`gh-pages` has a `base64url` PR to upgrade to 3.0.0. I'll keep this open to track the PR.
