### ISSUE TITLE
Functions are not sandboxed.

### ISSUE THREAD

**Issue by matimati433** [script-8/script-8.github.io#7]
Any casette can run any JS code just like in the console.
For example, a casette with:
`alert(1)`
will produce the effect of `alert(1)`.
`document.write("");` will execute document.write, which will remove everything from the page.
This makes everything unsafe, and everyone would need to check if a casette is okay to be run.

**Comment by gabrielflorit** [comment]
Agreed. One of the items on my list is to only allow a subset of JS.
