### ISSUE TITLE
SFX Music still playing from the editor when going to another tab

### ISSUE THREAD

**Issue by Tau5** [script-8/script-8.github.io#8]
Steps to reproduce:
1. Go to the SFX Editor
2. Press the PLAY button
3. Without pressing the STOP button go to CODE or RUN
4. Enjoy your Unstoppable song
Now if you go to SFX Editor you can see that you cant stop the music

**Comment by gabrielflorit** [comment]
Woops, thank you for catching this.

**Comment by gabrielflorit** [comment]
Fixed
